[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft = "9gcy363E4e8to6GCVje5xxLfqe6krVFfot2HHymteCod"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/fourb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
